repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.0'
    hooks:
      - id: mypy
        files: '(src)/.*\.py$'
        additional_dependencies: [pydantic]
        args: [--config-file=./pyproject.toml]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks

