name: Python CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up uv pip
        uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.1.12"
          uv-venv: ".venv"

      - name: Install dependencies
        run: |
          uv pip install -r requirements/requirements-dev.txt

      - name: Run ruff
        run: |
          uv pip install ruff
          ruff check .

      - name: Run mypy
        run: |
          uv pip install mypy
          mypy src

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml --cov-fail-under=80 tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
